### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by linkr** [fbsamples/audience-network#60] opened 2018-03-02 08:25 UTC
Have integrate error then compile.
Sdk 4.27

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}
gradle 3
`
Exception in thread "main" java.lang.AssertionError: Failed to load class when desugaring method com/facebook/ads/internal/view/c/c/a.onPlayerError(Lcom/google/android/exoplayer2/ExoPlaybackException;)V
	at com.google.devtools.build.android.desugar.TryWithResourcesRewriter$TryWithResourceVisitor.isMethodCallTargeted(TryWithResourcesRewriter.java:186)
	at com.google.devtools.build.android.desugar.TryWithResourcesRewriter$TryWithResourceVisitor.visitMethodInsn(TryWithResourcesRewriter.java:161)
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring$InterfaceInvocationRewriter.visitMethodInsn(InterfaceDesugaring.java:341)
	at org.objectweb.asm.tree.MethodInsnNode.accept(Unknown Source)
	at org.objectweb.asm.tree.InsnList.accept(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitEnd(LambdaDesugaring.java:383)
	at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
Caused by: java.lang.ClassNotFoundException: Class com.google.android.exoplayer2.ExoPlaybackException not found
	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.devtools.build.android.desugar.TryWithResourcesRewriter$TryWithResourceVisitor.isMethodCallTargeted(TryWithResourcesRewriter.java:183)
	... 16 more
`

**Comment by phzhou** [comment] 2018-04-09 07:11
Hi! 
We couldn't reproduce the issue, could you provide more details so we can try reproducing it?
How are you integrating the SDK? Do you use gradle dependency or including the "aar" file manually?
Could you also provide the build.gradle file so we can test?
Thanks!

**Comment by phzhou** [comment] 2018-05-14 05:36
Closing as there was not enough information for reproducing the issue

**Closed by phzhou** 2018-05-14 05:36 UTC

**Comment by linkr** [comment] 2018-05-29 08:49
Yes i include file manually. Problem not soleved yet.
My buil.gradle file very big and alson have modules.

**Comment by linkr** [comment] 2018-05-29 09:50
this issue resolving with adding android.enableD8.desugaring = true in gradle.properties file.

But compile time 5 min now =(

**Comment by vincentthai22** [comment] 2018-06-08 22:18
thanks for the comment as i am facing this issue too... my issue arised when i started using mopub 5.0.0@aar alongside with the AudienceNetwork.aar
