### ISSUE TITLE
Java.lang.IllegalStateException: no adapter ready to start in interstial ads

### ISSUE THREAD

**Issue by vishalpatelbacancy** [fbsamples/audience-network#58] opened 2018-01-20 09:55 UTC
java.lang.IllegalStateException: no adapter ready to start
                                                                           at com.facebook.ads.internal.DisplayAdController.b(Unknown Source)
                                                                           at com.facebook.ads.InterstitialAd.show(Unknown Source)
                                                                           at com.cellnuvo.cellnuvo.Activity.MainUserInterface.adPicker(MainUserInterface.java:1780)
                                                                           at com.cellnuvo.cellnuvo.Activity.MainUserInterface.onSwipe(MainUserInterface.java:2676)
                                                                           at com.cellnuvo.cellnuvo.Support.SimpleGestureFilter.onFling(SimpleGestureFilter.java:117)
                                                                           at android.view.GestureDetector.onTouchEvent(GestureDetector.java:667)
                                                                           at com.cellnuvo.cellnuvo.Support.SimpleGestureFilter.onTouchEvent(SimpleGestureFilter.java:44)
                                                                           at com.cellnuvo.cellnuvo.Activity.MainUserInterface.dispatchTouchEvent(MainUserInterface.java:2659)
                                                                           at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
                                                                           at android.view.View.dispatchPointerEvent(View.java:10228)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5345)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5181)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4621)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4674)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4640)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4782)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4648)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4839)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4621)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4674)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4640)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4648)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4621)
                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7307)
                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7185)
                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7146)
                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7417)
                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                           at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                           at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                           at android.os.Looper.loop(Looper.java:143)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by phzhou** [comment] 2018-01-23 03:52
Hi @vishalpatelbacancy would you be able to provide a sample code snippet that we can help reproduce the problem? Thanks!

**Comment by vishalpatelbacancy** [comment] 2018-01-24 06:10
i make two method

 ```
 public void fbAds(View v) {
        // Set listeners for the Interstitial Ad
        interstitialAd.setAdListener(new InterstitialAdListener() {
            @Override
            public void onInterstitialDisplayed(Ad ad) {
                // Interstitial displayed callback
                Log.e("fb ad", "Display");
            }

            @Override
            public void onInterstitialDismissed(Ad ad) {
                // Interstitial dismissed callback
                Log.e("fb ad", "Dismiss");
            }

            @Override
            public void onError(Ad ad, AdError adError) {
                // Ad error callback
                Toast.makeText(MainActivity.this, "Error: " + adError.getErrorMessage(),
                        Toast.LENGTH_LONG).show();
            }

            @Override
            public void onAdLoaded(Ad ad) {
                Log.e("fb ad", "loaded");
                // Show the ad when it's done loading.

            }

            @Override
            public void onAdClicked(Ad ad) {
                Log.e("fb ad", "");
                // Ad clicked callback
            }

            @Override
            public void onLoggingImpression(Ad ad) {
                Log.e("fb ad", "Dismiss");
                // Ad impression logged callback
            }
        });

        // For auto play video ads, it's recommended to load the ad
        // at least 30 seconds before it is shown
        interstitialAd.loadAd();
    }

```

second for show ad

```
public void show(View view) {

        interstitialAd.show();
    }
```


this was i make for demo purpose 

So what happen I take two button  load ads, show ads

after activity open i click on load ads  ,  and when i get    Log.e("fb ad", "loaded");  log after then i click on show ads,

the first time it works perfectly 


now I do same 

again click on load ads button    and when I get a log  "loaded "   i click to show ads


at that time it crashes.


i am not sure for a 2nd time 

sometimes it crashes on 3rd   or some time 4th also  its totally wired



I check at Facebook developer issue there were pending bugs same like me from 4 months  don't know why 

facebook cant figure out the issue ?

**Comment by phzhou** [comment] 2018-02-23 07:59
Hi @vishalpatelbacancy sorry it took so long to figure out. We are still trying to reproduce.
At the same time, could you let us know more about reproducing the issue?
What was the SDK version that you used?
What is the test device and OS version?
Thanks!

**Comment by phzhou** [comment] 2018-05-14 09:34
Closing due to not enough information to reproduce the issue

**Closed by phzhou** 2018-05-14 09:34 UTC
